CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Timestamp" timestamp with time zone NOT NULL,
        "UserId" integer,
        "Username" character varying(256) NOT NULL,
        "Action" character varying(100) NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "EntityId" character varying(100),
        "Details" text,
        "IpAddress" character varying(64),
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "SystemSettings" (
        "Key" character varying(150) NOT NULL,
        "Value" text,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(256) NOT NULL,
        "NormalizedUsername" character varying(256) NOT NULL,
        "DisplayName" character varying(256) NOT NULL,
        "Email" character varying(256),
        "Department" character varying(256),
        "PasswordHash" text,
        "ExternalId" text,
        "AuthSource" character varying(32) NOT NULL,
        "IsActive" boolean NOT NULL,
        "MustChangePassword" boolean NOT NULL,
        "FailedLoginCount" integer NOT NULL,
        "LockoutUntil" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "Contents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(300) NOT NULL,
        "Description" character varying(2000),
        "Body" text,
        "Type" integer NOT NULL,
        "Status" integer NOT NULL,
        "RequiresAcknowledgment" boolean NOT NULL,
        "Version" integer NOT NULL,
        "ExternalUrl" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "PublishedAt" timestamp with time zone,
        "CreatedById" integer,
        CONSTRAINT "PK_Contents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Contents_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "UserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "Assessments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(300) NOT NULL,
        "Description" character varying(2000),
        "ContentId" integer,
        "PassingPercentage" integer NOT NULL,
        "MaxAttempts" integer NOT NULL,
        "IsPublished" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Assessments" PRIMARY KEY ("Id"),
        CONSTRAINT ck_assessment_pass CHECK ("PassingPercentage" BETWEEN 0 AND 100),
        CONSTRAINT "FK_Assessments_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "ContentAttachments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContentId" integer NOT NULL,
        "FileName" character varying(300) NOT NULL,
        "StoredPath" character varying(500) NOT NULL,
        "ContentType" character varying(150) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "Kind" integer NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContentAttachments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContentAttachments_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "UserAcknowledgments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ContentId" integer NOT NULL,
        "ContentVersion" integer NOT NULL,
        "AcknowledgedAt" timestamp with time zone NOT NULL,
        "Status" character varying(32) NOT NULL,
        CONSTRAINT "PK_UserAcknowledgments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserAcknowledgments_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserAcknowledgments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "AssessmentAttempts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "AssessmentId" integer NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "Status" integer NOT NULL,
        "TotalQuestions" integer NOT NULL,
        "CorrectAnswers" integer NOT NULL,
        "TotalPoints" integer NOT NULL,
        "EarnedPoints" integer NOT NULL,
        "Percentage" numeric(5,2) NOT NULL,
        "PassingPercentageSnapshot" integer NOT NULL,
        "Passed" boolean,
        CONSTRAINT "PK_AssessmentAttempts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssessmentAttempts_Assessments_AssessmentId" FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AssessmentAttempts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "Questions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AssessmentId" integer NOT NULL,
        "Text" character varying(2000) NOT NULL,
        "Type" integer NOT NULL,
        "Points" integer NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Questions_Assessments_AssessmentId" FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "AssessmentAnswers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AttemptId" integer NOT NULL,
        "QuestionId" integer NOT NULL,
        "SelectedOptionIds" integer[] NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "PointsAwarded" integer NOT NULL,
        CONSTRAINT "PK_AssessmentAnswers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssessmentAnswers_AssessmentAttempts_AttemptId" FOREIGN KEY ("AttemptId") REFERENCES "AssessmentAttempts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AssessmentAnswers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE TABLE "QuestionOptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuestionId" integer NOT NULL,
        "Text" character varying(1000) NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_QuestionOptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuestionOptions_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AssessmentAnswers_AttemptId_QuestionId" ON "AssessmentAnswers" ("AttemptId", "QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentAnswers_QuestionId" ON "AssessmentAnswers" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentAttempts_AssessmentId_UserId" ON "AssessmentAttempts" ("AssessmentId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentAttempts_UserId" ON "AssessmentAttempts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_Assessments_ContentId" ON "Assessments" ("ContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_ContentAttachments_ContentId" ON "ContentAttachments" ("ContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_Contents_CreatedById" ON "Contents" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_Contents_Status_Type" ON "Contents" ("Status", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_QuestionOptions_QuestionId" ON "QuestionOptions" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_Questions_AssessmentId_SortOrder" ON "Questions" ("AssessmentId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_UserAcknowledgments_ContentId" ON "UserAcknowledgments" ("ContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UserAcknowledgments_UserId_ContentId_ContentVersion" ON "UserAcknowledgments" ("UserId", "ContentId", "ContentVersion");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE INDEX "IX_Users_ExternalId" ON "Users" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_NormalizedUsername" ON "Users" ("NormalizedUsername");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006104958_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261006104958_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006173411_AddContentAcknowledgmentText') THEN
    ALTER TABLE "Contents" ADD "AcknowledgmentText" character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006173411_AddContentAcknowledgmentText') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261006173411_AddContentAcknowledgmentText', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261009014228_AddContentCompletion') THEN
    CREATE TABLE "ContentCompletions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ContentId" integer NOT NULL,
        "ContentVersion" integer NOT NULL,
        "CompletedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContentCompletions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContentCompletions_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ContentCompletions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261009014228_AddContentCompletion') THEN
    CREATE INDEX "IX_ContentCompletions_ContentId" ON "ContentCompletions" ("ContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261009014228_AddContentCompletion') THEN
    CREATE UNIQUE INDEX "IX_ContentCompletions_UserId_ContentId_ContentVersion" ON "ContentCompletions" ("UserId", "ContentId", "ContentVersion");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261009014228_AddContentCompletion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261009014228_AddContentCompletion', '10.0.12');
    END IF;
END $EF$;
COMMIT;

